# Generated by Django 6.0.6 on 2026-06-09 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('seller', models.CharField(max_length=200, verbose_name='Seller')),
                ('numero_orden', models.CharField(max_length=100, unique=True, verbose_name='Número de orden')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('producto_nombre', models.CharField(blank=True, max_length=300, verbose_name='Nombre del producto')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado'), ('cerrado', 'Cerrado')], default='recibido', max_length=20, verbose_name='Estado')),
                ('condicion_producto', models.CharField(choices=[('nuevo', 'Nuevo / Sin uso'), ('bueno', 'Bueno'), ('danado', 'Dañado'), ('muy_danado', 'Muy dañado'), ('irreparable', 'Irreparable')], default='bueno', max_length=20, verbose_name='Condición del producto')),
                ('detalles_dano', models.TextField(blank=True, verbose_name='Detalles del daño')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_ingreso', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='devoluciones/%Y/%m/', verbose_name='Foto')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='returns.return')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
