# Generated by Django 4.2.30 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('America/Santiago', 'Chile - Santiago'), ('America/Punta_Arenas', 'Chile - Punta Arenas'), ('America/Argentina/Buenos_Aires', 'Argentina - Buenos Aires'), ('America/Bogota', 'Colombia - Bogota'), ('America/Lima', 'Peru - Lima'), ('America/La_Paz', 'Bolivia - La Paz'), ('America/Asuncion', 'Paraguay - Asuncion'), ('America/Montevideo', 'Uruguay - Montevideo'), ('America/Sao_Paulo', 'Brasil - Sao Paulo'), ('America/Mexico_City', 'Mexico - Ciudad de Mexico'), ('America/New_York', 'Estados Unidos - New York'), ('America/Los_Angeles', 'Estados Unidos - Los Angeles'), ('UTC', 'UTC')], default='America/Santiago', max_length=64, verbose_name='Zona horaria')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de plataforma',
                'verbose_name_plural': 'Configuración de plataforma',
            },
        ),
    ]
