# Generated by Django 4.2.30 on 2026-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0011_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='condicion_producto',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('caja_danada', 'Caja Dañada'), ('danado', 'Dañado'), ('dano_estetico', 'Daño Estetico'), ('extraviado', 'Extraviado')], default='nuevo', max_length=20, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='return',
            name='grado',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('D', 'D'), ('E', 'Extraviado')], default='A', max_length=1, verbose_name='Grado'),
        ),
    ]
