# Generated by Django 4.2.30 on 2026-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0012_alter_return_condicion_producto_alter_return_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='sub_danos',
            field=models.JSONField(blank=True, default=list, verbose_name='Sub daños'),
        ),
    ]
