# Generated by Django 4.2.30 on 2026-06-28 07:55

from django.db import migrations, models
import returns.models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0013_return_sub_danos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnphoto',
            name='foto',
            field=models.ImageField(upload_to=returns.models.return_photo_upload_to, verbose_name='Foto'),
        ),
    ]
