# Generated by Django 4.2.30 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0014_alter_returnphoto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='ingresado_bodega',
            field=models.BooleanField(default=False, verbose_name='Ingresado a bodega'),
        ),
    ]
