# Generated by Django 4.2.30 on 2026-07-10 04:35

from django.db import migrations, models


def preserve_existing_paid_amounts(apps, schema_editor):
    Appeal = apps.get_model('returns', 'Appeal')
    Appeal.objects.filter(status='pagado').exclude(estado_cuenta='').update(
        monto_devuelto=models.F('estado_cuenta')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0015_return_ingresado_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='monto_devuelto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Monto devuelto'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='estado_cuenta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Monto apelado'),
        ),
        migrations.RunPython(preserve_existing_paid_amounts, migrations.RunPython.noop),
    ]
